#
# application.yml — главный конфигурационный файл Spring Boot.

server:
  port: 8081
spring:
  datasource:
    url:


Что нужно сделать:
  - Указать настройки подключения к базе данных.
  - Указать порт приложения.
  - Настроить параметры безопасности и JWT.
  - Включить Swagger UI.
